blank_issues_enabled: true
contact_links:
  - name: ggMCP4VSCode Q&A
    url: https://github.com/bugstan/ggMCP4VSCode/discussions/categories/q-a
    about: Please use the discussion section for general questions and support
  - name: ggMCP4VSCode Documentation
    url: https://github.com/bugstan/ggMCP4VSCode#readme
    about: Please check the project documentation for more information